[#952] Added laggon update variable.
drevops/drevops pull request #1209
Opened 2024-02-28 08:06 UTC by richardgaunt

## Checklist before requesting a review

- [x] I have formatted the subject to include ticket number as `[#123] Verb in past tense with dot at the end.`
- [x] I have added a link to the issue tracker
- [x] I have provided information in `Changed` section about WHY something was done if this was not a normal implementation
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run new and existing relevant tests locally with my changes, and they passed
- [ ] I have provided screenshots, where applicable

## Changed

1. Updated to lagoon update variable rather than add and delete.
2. Updated tests.

## Screenshots

2024-02-28 08:06 UTC, richardgaunt commented on .drevops/tests/bats/deployment1.bats
> +  assert_contains "-l testlagoon update variable -p testproject -e testbranch -N DREVOPS_PROVISION_OVERRIDE_DB -V 0 -S global" "$(mock_get_call_args "${mock_lagoon}" 4)"
Had trouble running locally - with the deployment code we could test it in isolation as unit tests rather than deploying actual builds.

2024-02-28 19:54 UTC, AlexSkrypnyk commented on .drevops/tests/bats/deployment1.bats
> +  assert_contains "-l testlagoon update variable -p testproject -e testbranch -N DREVOPS_PROVISION_OVERRIDE_DB -V 0 -S global" "$(mock_get_call_args "${mock_lagoon}" 4)"
@richardgaunt the numbers (`3`, `4` etc.) at the end of the assertions need to be updated throughout the whole test after the order being modified (this is due to using an old way of asserting that commands run in the order)

```
assert_contains "-l testlagoon update variable -p testproject -e testbranch -N DREVOPS_PROVISION_OVERRIDE_DB -V 0 -S global" "$(mock_get_call_args "${mock_lagoon}" 3)"
```

2024-02-28 19:56 UTC, AlexSkrypnyk commented
@richardgaunt 
could you please confirm that you have tested this code for 2 cases on real Lagoon instance:
1. The env is brand new
2. The env already exists and the deployment is a follow-up deployment

This is to make sure that Lagoon's API supports running `update` on non-existing variable.

2024-02-28 19:57 UTC, AlexSkrypnyk requested changes
@richardgaunt 
Could you please update tests. Thank you

2024-02-29 02:27 UTC, richardgaunt commented
> @richardgaunt could you please confirm that you have tested this code for 2 cases on real Lagoon instance:
> 
>     1. The env is brand new
> 
>     2. The env already exists and the deployment is a follow-up deployment
> 
> 
> This is to make sure that Lagoon's API supports running `update` on non-existing variable.

Tested with the PR new environment creation, tested with overriding a database. All worked correctly and the variables were correct values after deploying.

2024-03-01 00:08 UTC, AlexSkrypnyk approved these changes

2024-03-01 05:51 UTC, merged